[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "alter-ai-twin"
version = "0.0.1"
authors = [
  { name="Raghav B. Venkataramaiyer", email="bv.raghav@thapar.edu" },
]
description = "Alter AI Twin"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pandas",
    "scipy",
    "pydantic",
    "pydantic-settings"
]

[tool.hatch.build.targets.wheel]
packages = ["code/src"]
